/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DichHaiRouteImport } from './routes/dich-hai'
import { Route as DinhDuongRouteImport } from './routes/dinh-duong'
import { Route as MoiTruongRouteImport } from './routes/moi-truong'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DichHaiRoute = DichHaiRouteImport.update({
  id: '/dich-hai',
  path: '/dich-hai',
  getParentRoute: () => rootRouteImport,
} as any)
const DinhDuongRoute = DinhDuongRouteImport.update({
  id: '/dinh-duong',
  path: '/dinh-duong',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiTruongRoute = MoiTruongRouteImport.update({
  id: '/moi-truong',
  path: '/moi-truong',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dich-hai': typeof DichHaiRoute
  '/dinh-duong': typeof DinhDuongRoute
  '/moi-truong': typeof MoiTruongRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dich-hai': typeof DichHaiRoute
  '/dinh-duong': typeof DinhDuongRoute
  '/moi-truong': typeof MoiTruongRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dich-hai': typeof DichHaiRoute
  '/dinh-duong': typeof DinhDuongRoute
  '/moi-truong': typeof MoiTruongRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dich-hai' | '/dinh-duong' | '/moi-truong'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dich-hai' | '/dinh-duong' | '/moi-truong'
  id: '__root__' | '/' | '/dich-hai' | '/dinh-duong' | '/moi-truong'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DichHaiRoute: typeof DichHaiRoute
  DinhDuongRoute: typeof DinhDuongRoute
  MoiTruongRoute: typeof MoiTruongRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-hai': {
      id: '/dich-hai'
      path: '/dich-hai'
      fullPath: '/dich-hai'
      preLoaderRoute: typeof DichHaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinh-duong': {
      id: '/dinh-duong'
      path: '/dinh-duong'
      fullPath: '/dinh-duong'
      preLoaderRoute: typeof DinhDuongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-truong': {
      id: '/moi-truong'
      path: '/moi-truong'
      fullPath: '/moi-truong'
      preLoaderRoute: typeof MoiTruongRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DichHaiRoute: DichHaiRoute,
  DinhDuongRoute: DinhDuongRoute,
  MoiTruongRoute: MoiTruongRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
